[0m07:06:07.680452 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffa0854a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff9faf43a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff9faf4370>]}


============================== 07:06:07.687135 | 43b4c8c6-e4bb-41d3-8e8a-208e13ab7be6 ==============================
[0m07:06:07.687135 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:06:07.688032 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt init my_dbt_project', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m07:06:07.708357 [info ] [MainThread]: A project called my_dbt_project already exists here.
[0m07:06:07.710686 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.04012158, "process_in_blocks": "70384", "process_kernel_time": 0.517734, "process_mem_max_rss": "96348", "process_out_blocks": "1290", "process_user_time": 0.886122}
[0m07:06:07.711150 [debug] [MainThread]: Command `dbt init` succeeded at 07:06:07.711068 after 0.04 seconds
[0m07:06:07.714365 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffa0854a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff9f8f5510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff9f8f4670>]}
[0m07:06:07.715022 [debug] [MainThread]: Flushing usage events
[0m07:06:09.378001 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:07:14.870630 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8f54c820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8e54e890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8e54d870>]}


============================== 07:07:14.873023 | fdfd84a9-02e4-49dc-97f6-3bd8596cd238 ==============================
[0m07:07:14.873023 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:07:14.873436 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init my_dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m07:07:14.877923 [info ] [MainThread]: A project called my_dbt_project already exists here.
[0m07:07:14.878602 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.011234625, "process_in_blocks": "0", "process_kernel_time": 0.245632, "process_mem_max_rss": "92600", "process_out_blocks": "2", "process_user_time": 0.740925}
[0m07:07:14.878855 [debug] [MainThread]: Command `dbt init` succeeded at 07:07:14.878809 after 0.01 seconds
[0m07:07:14.879108 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8f54c820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8e54e890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8e54f220>]}
[0m07:07:14.879309 [debug] [MainThread]: Flushing usage events
[0m07:07:15.931336 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:11:17.819289 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb6750850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb574e8f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb574d8d0>]}


============================== 07:11:17.822817 | 3d4aa7ed-440d-4f2b-93c4-f39aefa488c2 ==============================
[0m07:11:17.822817 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:11:17.823264 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init my_dbt_project', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m07:11:17.829309 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/site-packages/dbt/include/starter_project
[0m07:11:17.848130 [info ] [MainThread]: 
Your new dbt project "my_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m07:11:17.849365 [info ] [MainThread]: Setting up your profile.
[0m07:11:17.851249 [error] [MainThread]: Encountered an error:
while scanning for the next token
found character '\t' that cannot start any token
  in "/root/.dbt/profiles.yml", line 6, column 2
[0m07:11:17.855608 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 248, in setup_profile
    if not self.check_if_can_write_profile(profile_name=profile_name):
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 209, in check_if_can_write_profile
    profiles = yaml.safe_load(f) or {}
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/root/.dbt/profiles.yml", line 6, column 2

[0m07:11:17.857204 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.040722374, "process_in_blocks": "496", "process_kernel_time": 0.201532, "process_mem_max_rss": "92832", "process_out_blocks": "18", "process_user_time": 0.701888}
[0m07:11:17.857540 [debug] [MainThread]: Command `dbt init` failed at 07:11:17.857472 after 0.04 seconds
[0m07:11:17.857795 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb6750850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb5603880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb56037f0>]}
[0m07:11:17.858101 [debug] [MainThread]: Flushing usage events
[0m07:11:19.661189 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:14:46.045526 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8e2849a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8d4f83a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8d4f81f0>]}


============================== 07:14:46.053020 | c45376e9-c7cc-4282-bf2d-576dfefcba3c ==============================
[0m07:14:46.053020 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:14:46.053458 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/root/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init my_dbt_project', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m07:14:46.062059 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/site-packages/dbt/include/starter_project
[0m07:14:46.079429 [info ] [MainThread]: 
Your new dbt project "my_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m07:14:46.080233 [info ] [MainThread]: Setting up your profile.
[0m07:14:46.081694 [error] [MainThread]: Encountered an error:
while scanning for the next token
found character '\t' that cannot start any token
  in "/root/.dbt/profiles.yml", line 6, column 2
[0m07:14:46.088743 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 248, in setup_profile
    if not self.check_if_can_write_profile(profile_name=profile_name):
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 209, in check_if_can_write_profile
    profiles = yaml.safe_load(f) or {}
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/root/.dbt/profiles.yml", line 6, column 2

[0m07:14:46.090630 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.0499495, "process_in_blocks": "0", "process_kernel_time": 0.599207, "process_mem_max_rss": "97464", "process_out_blocks": "1306", "process_user_time": 0.927737}
[0m07:14:46.091157 [debug] [MainThread]: Command `dbt init` failed at 07:14:46.091085 after 0.05 seconds
[0m07:14:46.091741 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8e2849a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8d3fb6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff8d3fb9a0>]}
[0m07:14:46.092013 [debug] [MainThread]: Flushing usage events
[0m07:14:47.636667 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:15:40.913514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff960807f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94f02b60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94f02bc0>]}


============================== 07:15:40.915513 | a5cad865-05bf-4448-8114-d49f65b831eb ==============================
[0m07:15:40.915513 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:15:40.917992 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init my_dbt_project', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m07:15:40.923702 [info ] [MainThread]: A project called my_dbt_project already exists here.
[0m07:15:40.924846 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.061761416, "process_in_blocks": "0", "process_kernel_time": 0.331061, "process_mem_max_rss": "93564", "process_out_blocks": "2", "process_user_time": 0.738204}
[0m07:15:40.925324 [debug] [MainThread]: Command `dbt init` succeeded at 07:15:40.925253 after 0.06 seconds
[0m07:15:40.925626 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff960807f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94f018a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94f02c20>]}
[0m07:15:40.925903 [debug] [MainThread]: Flushing usage events
[0m07:15:42.006575 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:15:58.895322 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb53587c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb4206b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb4206bf0>]}


============================== 07:15:58.897175 | 606e1b52-79d4-4e0c-816a-1b332eff9c55 ==============================
[0m07:15:58.897175 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:15:58.897724 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m07:15:58.903903 [info ] [MainThread]: dbt version: 1.10.4
[0m07:15:58.904176 [info ] [MainThread]: python version: 3.10.18
[0m07:15:58.904504 [info ] [MainThread]: python path: /usr/local/bin/python3.10
[0m07:15:58.904777 [info ] [MainThread]: os info: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[0m07:16:03.346909 [info ] [MainThread]: Using profiles dir at /root/.dbt
[0m07:16:03.347602 [info ] [MainThread]: Using profiles.yml file at /root/.dbt/profiles.yml
[0m07:16:03.348075 [info ] [MainThread]: Using dbt_project.yml file at /usr/app/dbt_project.yml
[0m07:16:03.348466 [info ] [MainThread]: adapter type: bigquery
[0m07:16:03.348915 [info ] [MainThread]: adapter version: 1.10.0
[0m07:16:03.349605 [info ] [MainThread]: Configuration:
[0m07:16:03.349901 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m07:16:03.350137 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m07:16:03.350396 [info ] [MainThread]: Required dependencies:
[0m07:16:03.350736 [debug] [MainThread]: Executing "git --help"
[0m07:16:03.378468 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m07:16:03.379016 [debug] [MainThread]: STDERR: "b''"
[0m07:16:03.379290 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m07:16:03.379567 [info ] [MainThread]: Connection:
[0m07:16:03.379932 [info ] [MainThread]:   method: service-account
[0m07:16:03.380327 [info ] [MainThread]:   database: your-gcp-project-id
[0m07:16:03.380725 [info ] [MainThread]:   execution_project: your-gcp-project-id
[0m07:16:03.380952 [info ] [MainThread]:   schema: your_dataset
[0m07:16:03.381376 [info ] [MainThread]:   location: None
[0m07:16:03.382055 [info ] [MainThread]:   priority: None
[0m07:16:03.382344 [info ] [MainThread]:   maximum_bytes_billed: None
[0m07:16:03.383226 [info ] [MainThread]:   impersonate_service_account: None
[0m07:16:03.384649 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m07:16:03.386512 [info ] [MainThread]:   job_retries: 1
[0m07:16:03.387514 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m07:16:03.388685 [info ] [MainThread]:   job_execution_timeout_seconds: None
[0m07:16:03.392330 [info ] [MainThread]:   timeout_seconds: None
[0m07:16:03.396894 [info ] [MainThread]:   client_id: None
[0m07:16:03.398378 [info ] [MainThread]:   token_uri: None
[0m07:16:03.404105 [info ] [MainThread]:   compute_region: None
[0m07:16:03.409676 [info ] [MainThread]:   dataproc_cluster_name: None
[0m07:16:03.410516 [info ] [MainThread]:   gcs_bucket: None
[0m07:16:03.411359 [info ] [MainThread]:   dataproc_batch: None
[0m07:16:03.412456 [info ] [MainThread]: Registered adapter: bigquery=1.10.0
[0m07:16:03.557940 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m07:16:03.558365 [debug] [MainThread]: On debug: select 1 as id
[0m07:16:03.558640 [debug] [MainThread]: Opening a new connection, currently in state init
[0m07:16:04.694522 [error] [MainThread]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=your-gcp-project-id&j=bq:None:be3c16c7-90f5-41dd-96eb-2bd66939ff94&page=queryresults
[0m07:16:04.698232 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m07:16:04.699473 [info ] [MainThread]: [31m2 checks failed:[0m
[0m07:16:04.700682 [info ] [MainThread]: Project loading failed for the following reason:
 project path </usr/app/dbt_project.yml> not found

[0m07:16:04.702799 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  ProjectId must be non-empty

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m07:16:04.705365 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 5.842055, "process_in_blocks": "283288", "process_kernel_time": 1.986961, "process_mem_max_rss": "334068", "process_out_blocks": "278", "process_user_time": 2.737055}
[0m07:16:04.706936 [debug] [MainThread]: Command `dbt debug` failed at 07:16:04.706644 after 5.84 seconds
[0m07:16:04.707859 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m07:16:04.708863 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffb53587c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff90e26d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff90e27040>]}
[0m07:16:04.709984 [debug] [MainThread]: Flushing usage events
[0m07:16:05.778932 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:17:07.231673 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff967847f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff95606b60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff95606bc0>]}


============================== 07:17:07.233841 | be5ffcea-905b-418b-b722-58169c513a27 ==============================
[0m07:17:07.233841 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:17:07.234424 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt init my_dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m07:17:07.238912 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/site-packages/dbt/include/starter_project
[0m07:17:07.248957 [info ] [MainThread]: 
Your new dbt project "my_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m07:17:07.249327 [info ] [MainThread]: Setting up your profile.
[0m07:17:10.202582 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 3.0035982, "process_in_blocks": "0", "process_kernel_time": 0.147397, "process_mem_max_rss": "93612", "process_out_blocks": "11", "process_user_time": 0.704901}
[0m07:17:10.203775 [debug] [MainThread]: Command `dbt init` succeeded at 07:17:10.203661 after 3.01 seconds
[0m07:17:10.204384 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff967847f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff961209a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff96122710>]}
[0m07:17:10.205020 [debug] [MainThread]: Flushing usage events
[0m07:17:11.248314 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m07:17:49.032137 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffab7547f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffaa60aec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffaa60af20>]}


============================== 07:17:49.034309 | 9f3e2237-b332-4a37-be35-d65f89a9f6f3 ==============================
[0m07:17:49.034309 [info ] [MainThread]: Running with dbt=1.10.4
[0m07:17:49.034806 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m07:17:49.039379 [info ] [MainThread]: dbt version: 1.10.4
[0m07:17:49.039694 [info ] [MainThread]: python version: 3.10.18
[0m07:17:49.040018 [info ] [MainThread]: python path: /usr/local/bin/python3.10
[0m07:17:49.040315 [info ] [MainThread]: os info: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[0m07:17:50.450103 [info ] [MainThread]: Using profiles dir at /root/.dbt
[0m07:17:50.450818 [info ] [MainThread]: Using profiles.yml file at /root/.dbt/profiles.yml
[0m07:17:50.451346 [info ] [MainThread]: Using dbt_project.yml file at /usr/app/dbt_project.yml
[0m07:17:50.451724 [info ] [MainThread]: adapter type: bigquery
[0m07:17:50.452020 [info ] [MainThread]: adapter version: 1.10.0
[0m07:17:50.452486 [info ] [MainThread]: Configuration:
[0m07:17:50.452743 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m07:17:50.453117 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m07:17:50.453431 [info ] [MainThread]: Required dependencies:
[0m07:17:50.453688 [debug] [MainThread]: Executing "git --help"
[0m07:17:50.455747 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m07:17:50.456053 [debug] [MainThread]: STDERR: "b''"
[0m07:17:50.456273 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m07:17:50.456525 [info ] [MainThread]: Connection:
[0m07:17:50.456863 [info ] [MainThread]:   method: service-account
[0m07:17:50.457109 [info ] [MainThread]:   database: your-gcp-project-id
[0m07:17:50.457356 [info ] [MainThread]:   execution_project: your-gcp-project-id
[0m07:17:50.457593 [info ] [MainThread]:   schema: your_dataset
[0m07:17:50.457886 [info ] [MainThread]:   location: None
[0m07:17:50.458132 [info ] [MainThread]:   priority: None
[0m07:17:50.458391 [info ] [MainThread]:   maximum_bytes_billed: None
[0m07:17:50.458663 [info ] [MainThread]:   impersonate_service_account: None
[0m07:17:50.458907 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m07:17:50.459275 [info ] [MainThread]:   job_retries: 1
[0m07:17:50.459548 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m07:17:50.459774 [info ] [MainThread]:   job_execution_timeout_seconds: None
[0m07:17:50.460062 [info ] [MainThread]:   timeout_seconds: None
[0m07:17:50.460392 [info ] [MainThread]:   client_id: None
[0m07:17:50.460625 [info ] [MainThread]:   token_uri: None
[0m07:17:50.460880 [info ] [MainThread]:   compute_region: None
[0m07:17:50.461105 [info ] [MainThread]:   dataproc_cluster_name: None
[0m07:17:50.461353 [info ] [MainThread]:   gcs_bucket: None
[0m07:17:50.461637 [info ] [MainThread]:   dataproc_batch: None
[0m07:17:50.461991 [info ] [MainThread]: Registered adapter: bigquery=1.10.0
[0m07:17:50.551329 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m07:17:50.551788 [debug] [MainThread]: On debug: select 1 as id
[0m07:17:50.552054 [debug] [MainThread]: Opening a new connection, currently in state init
[0m07:17:52.410264 [error] [MainThread]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=your-gcp-project-id&j=bq:None:1b36d5d0-62c1-4979-a22d-b926780f1199&page=queryresults
[0m07:17:52.469146 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m07:17:52.473371 [info ] [MainThread]: [31m2 checks failed:[0m
[0m07:17:52.475062 [info ] [MainThread]: Project loading failed for the following reason:
 project path </usr/app/dbt_project.yml> not found

[0m07:17:52.480058 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  ProjectId must be non-empty

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m07:17:52.496220 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 3.4926538, "process_in_blocks": "0", "process_kernel_time": 0.417969, "process_mem_max_rss": "334508", "process_out_blocks": "14", "process_user_time": 2.795961}
[0m07:17:52.501804 [debug] [MainThread]: Command `dbt debug` failed at 07:17:52.500511 after 3.50 seconds
[0m07:17:52.505681 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m07:17:52.509918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffffab7547f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff871d33a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff872237f0>]}
[0m07:17:52.517896 [debug] [MainThread]: Flushing usage events
[0m07:17:53.690753 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:37:52.529536 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff95c849d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94c5d630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94c5d5d0>]}


============================== 08:37:52.533368 | c722d4dd-c82d-4869-b7b9-48966688f540 ==============================
[0m08:37:52.533368 [info ] [MainThread]: Running with dbt=1.10.4
[0m08:37:52.533840 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m08:38:03.233426 [error] [MainThread]: Encountered an error:

[0m08:38:03.241840 [error] [MainThread]: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 324, in run
    project_name = self.get_valid_project_name()
  File "/usr/local/lib/python3.10/site-packages/dbt/task/init.py", line 278, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/usr/local/lib/python3.10/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "/usr/local/lib/python3.10/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m08:38:03.247391 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 10.7499695, "process_in_blocks": "64", "process_kernel_time": 0.22212, "process_mem_max_rss": "97732", "process_out_blocks": "1292", "process_user_time": 0.766416}
[0m08:38:03.248702 [debug] [MainThread]: Command `dbt init` failed at 08:38:03.248517 after 10.75 seconds
[0m08:38:03.249802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff95c849d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94b54d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94b16ec0>]}
[0m08:38:03.251001 [debug] [MainThread]: Flushing usage events
[0m08:38:04.337445 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:38:51.057739 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff7eb50a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff7db316c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff7db31660>]}


============================== 08:38:51.061298 | f42e7a75-3ffe-423a-b137-cc85bcdada69 ==============================
[0m08:38:51.061298 [info ] [MainThread]: Running with dbt=1.10.4
[0m08:38:51.061727 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/root/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init my_dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m08:38:51.068731 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.10/site-packages/dbt/include/starter_project
[0m08:38:51.079576 [info ] [MainThread]: 
Your new dbt project "my_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m08:38:51.079996 [info ] [MainThread]: Setting up your profile.
[0m08:38:52.976672 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 1.9465413, "process_in_blocks": "0", "process_kernel_time": 0.256247, "process_mem_max_rss": "97464", "process_out_blocks": "1299", "process_user_time": 0.736711}
[0m08:38:52.978595 [debug] [MainThread]: Command `dbt init` succeeded at 08:38:52.978288 after 1.95 seconds
[0m08:38:52.980693 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff7eb50a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff7de73880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff7da55210>]}
[0m08:38:52.982436 [debug] [MainThread]: Flushing usage events
[0m08:38:54.009963 [debug] [MainThread]: An error was encountered while trying to flush usage events
